databases:
  - name: rubydockerdb
    databaseName: rubydockerdb
    user: rubydockerdb

services:
  - type: web
    name: rubydockercomm
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rubydockerdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
